[package]
name = "educational-missile-physics"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.14"
bevy = { version = "0.18.0", features = ["bevy_camera_controller", "debug", "dynamic_linking", "free_camera"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"
